# Generated by Django 5.1.4 on 2024-12-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_course_degree_level_course_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
