# Generated by Django 5.1.4 on 2024-12-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
