# Generated by Django 5.1.4 on 2024-12-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_fully_registered',
            field=models.BooleanField(default=False),
        ),
    ]
