# Generated by Django 5.1.4 on 2024-12-12 09:30

from django.db import migrations
from schedules.models import EvaluationType


evaluation_types = [
    'Final Exam',
    'Midterm Exam',
    'Assignment',
    'Quiz',
    'Project',
    'Presentation',
    'Written Test',
]


def create_default_evaluation_types(apps, schema_editor):
    for evaluation_type in evaluation_types:
        EvaluationType.objects.create(name=evaluation_type)


def remove_default_evaluation_types(apps, schema_editor):
    EvaluationType.objects.filter(name__in=evaluation_types).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_evaluationtype'),
    ]

    operations = [
        migrations.RunPython(create_default_evaluation_types, reverse_code=remove_default_evaluation_types),
    ]
