# Generated by Django 5.1.4 on 2024-12-12 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_auto_20241212_1330'),
        ('universities', '0003_university_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveryWeekEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_week', models.PositiveIntegerField()),
                ('max_points', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.course')),
                ('evaluation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.evaluationtype')),
                ('exact_evaluation_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exact_evaluation_date', to='schedules.everyhourschedule')),
            ],
        ),
    ]
